### PR TITLE
Fix missing `libgfortran4` dependency in CI

### LINKED ISSUE #42: CI cannot install gfortran anymore
Recently the CI job is failing at:
```
Unable to locate package libgfortran4
```
This is probably (?) due to newest version of Ubuntu (?, ie at ubuntu-latest). Think how to fix this.

Any ideas @ml-evs ?

### PR DESCRIPTION
**Pull request by ml-evs**
Closes #42 by installing libgfortran4 from conda-forge in the CI.

### CODE REVIEW

**Comment by ml-evs** [comment]
There's something weird happening with the miniconda action I'm using where either the Python version or the base environment isn't being set properly. Will try to figure this out soon.

**Comment by pedrobcst** [comment]
Thanks alot of the trials. I was thinking if it would work if we just set up ubuntu to a fixed version (maybe even 18.04 is fine)? I will try to see if it is possible install via apt in any other manner. This is just too sudden and I got caught out surprise

**Comment by pedrobcst** [comment]
Hey Evan, I made a new branch (sorry bout that) with fixed ubuntu version to 20.04 and that seems to run fine (also it seems we need to fix scipy version).

But currently seems that something is going on with OQMD structures and the OPTIMADE OQMD tests are failing. I will take a look at that later, but fixing ubuntu to 20.04 seems to work for now, and might be a good enough bandaid fix, until we can figure out how to do that for later versions of it.

**Comment by ml-evs** [comment]
Finally got the magic incantation right @pedrobcst (you have to explicitly set the shell to use the miniconda action). This PR uses the latest ubuntu and the conda-forge repos to get libgfortran.

I'll leave it up to you whether you want to use it or just pin to 20.04!

**Comment by pedrobcst** [comment]
Hey man thanks for the hardwork!

I think its better to use the conda version just to ensure that it will work with any ubuntu version. Thanks so much for that I will merge it into main.

**Review by pedrobcst — APPROVED** [review]

**Pull request merged**
