### PR TITLE
Package library and add GitHub actions CI

### PR DESCRIPTION
**Pull request by ml-evs**
Hi @pedrobcst, this PR does the following:

- Make the package installable with pip by adding a `setup.cfg`
    - I also removed some of the `sys.path` hacks that were required without this packaging
- Add GitHub actions CI to simply run pytest with an attached MongoDB

Caveats:

- The tests seem to fail at the moment due to issues with hard-coded paths (I fixed the obvious ones).
- Some tests need the MP_API_KEY to be set, which isn't suitable for running in the CI.
- GSAS seems to work, but required installing `libgfortran4` and `subversion` on top of the default ubuntu image. Have you tried using the `conda-forge` package with `conda install gsas2pkg -c defaults -c conda-forge -c briantoby`?

You can see the CI actually running the tests on my fork: https://github.com/ml-evs/Xerus/runs/5350440079?check_suite_focus=true

### CODE REVIEW

**Comment by pedrobcst** [comment]
Hi @ml-evs, thanks alot for this PR. I think this will be important going forward, but there is few things I might have to explain about why they exist.
> The tests seem to fail at the moment due to issues with hard-coded paths (I fixed the obvious ones).
Some tests need the MP_API_KEY to be set, which isn't suitable for running in the CI.
GSAS seems to work, but required installing libgfortran4 and subversion on top of the default ubuntu image. Have you tried using the conda-forge package with conda install gsas2pkg -c defaults -c conda-forge -c briantoby?

The path hacks were actually (if I remember well) necessary because of how GSASII is packaged. Actually, the biggest challenge is to make things work nicely with GSASII. Most of the time, the Conda installation will simple not go forward depending on OS etc. This is the main reason I bundled GSASII inside Xerus after I got things working well. Also too extend to other unix systems all it was needed was to get the current fortran binaries provided by them, and sadly this does not work for Windows (just a comment).

Another issue is, that we have to manually append the scriptable path to the sys, otherwise it will not be able to find it (even if you do by conda install). Although it seems there is a 'lightweight' distribution of only the scriptable package available if you go around the docs, I found that too late. The third issue is, Xerus is using a older version of GSASII. All the newest releases of GSASII do not play well along, and usually get stuck well trying to refine some 'wrong' combination. Currently, it will just return a high Rwp, but the newest versions seems to get stuck in a never ending calculation. I didnt have time to trackdown what causes this issue to write a bug report though.

Regarding the tests, I admit they are not the best. They were designed to check if installation was set correct (so it could connect to databases and such). I honestly have to think on how to write a better set of tests. I am wondering if its possible to obtain a 'dummy' API KEY to use for tests, or we just remove the materials project API key requirement...

**Comment by pedrobcst** [comment]
I see! After I finished making a working optimade querier for both MP/OQMD (I think we can leave COD for now..), I will merge this. Regarding the tests I think I had an idea, let me know what you think.

1. We seperate the tests into 'CI_tests' (that we used to check with nothing broken), and this we do the following:
 - We remove the 'settings_test' (this is actually just checking the API KEY is correctly set)
 - We use OPTIMADE implementation to query MaterialsProject (and use the 'usual' ones for the rest) to get CIFs when testing the refinement / solvers (simulations etc)
 - This ofc means that the 'real' MP querier will never be tested, but since its done directly by pymatgen I dont believe there is a reason that will stop working.
 2. We just set a different test of set which only purpose is to check with the installation (ie, settings etc) was done currently when someone wnat to use.

This manner I can always check if the 'core' part is running fine, while testing the settings is more on a user case basis

**Comment by ml-evs** [comment]
> I see! After I finished making a working optimade querier for both MP/OQMD (I think we can leave COD for now..), I will merge this. Regarding the tests I think I had an idea, let me know what you think.
> 
>     1. We seperate the tests into 'CI_tests' (that we used to check with nothing broken), and this we do the following:
> 
>     * We remove the 'settings_test' (this is actually just checking the API KEY is correctly set)
> 
I think I have already done 1, by defining a pytest "mark" called `user` and then running the tests with `pytest -m "not user"` in the CI. This excludes the settings tests (but keeps the GSAS setup test). I can try to push this today --- there was one outstanding issue with a missing `cif.json` file that I cannot track down.

>     * We use OPTIMADE implementation to query MaterialsProject (and use the 'usual' ones for the rest) to get CIFs when testing the refinement / solvers (simulations etc)

I think I also have the mock MPRester working too, so we can also test MP directly without an API key (it just fakes the same response) and without needing to get the OPTIMADE stuff implemented first.

>     2. We just set a different test of set which only purpose is to check with the installation (ie, settings etc) was done currently when someone wnat to use.
> 
This can now be run with `pytest -m "user"`, or just by default `pytest` which will run all tests.

**Comment by pedrobcst** [comment]
> I think I have already done 1, by defining a pytest "mark" called user and then running the tests with pytest -m "not user" in the CI. This excludes the settings tests (but keeps the GSAS setup test). I can try to push this today --- there was one outstanding issue with a missing cif.json file that I cannot track down.

> I think I also have the mock MPRester working too, so we can also test MP directly without an API key (it just fakes the same response) and without needing to get the OPTIMADE stuff implemented first.

Sorry I think I forgot to explain a bit more in detail the tests and why I think the OPTIMADE route might the best. One of the tests is actually running Xerus in a 'common' dataset (that is, my experimental data that I know what result is supposed to be) to test few of the solvers method implemented. In this manner what happens is, XERUS will run the full analysis with different settings. This means the following:

1. Since when someone it first run there will be no structure located in the database, Xerus will do a multiquery for 'Ho', 'B' and 'Ho-B'. Since multiquery be default will run materialsproject MPRester, and if its not well configured it will not run. This might take a time because each CIF currently is being tested indiviuadlly by GSASII. There is a few reasons why I have done this, but just to make it short it is, some structures (especially coming from COD) will 'break' GSASII (It will have some issue during refinement, leading to a FloatingPointError, which can only be fixed by restarting the script). Currently this is slow,, and I am still thinking on what is the best way to solve this.
2. Then after everything is downloaded we will do set of analysis (after everything is downloaded)

I believe the cif.json issue is happening in the GSASII tester part, probably because there was an issue downloading the structures. This is why I think we should set CI with optimade MP, because even if we mock, in the end he still needs the structures.

I am sorry I am telling this now, I should had told you before exactly what the tests are doing.

**Comment by ml-evs** [comment]
> Sorry I think I forgot to explain a bit more in detail the tests and why I think the OPTIMADE route might the best. One of the tests is actually running Xerus in a 'common' dataset (that is, my experimental data that I know what result is supposed to be) to test few of the solvers method implemented. In this manner what happens is, XERUS will run the full analysis with different settings. This means the following:
> 
>     1. Since when someone it first run there will be no structure located in the database, Xerus will do a multiquery for 'Ho', 'B' and 'Ho-B'. Since multiquery be default will run materialsproject MPRester, and if its not well configured it will not run. This might take a time because each CIF currently is being tested indiviuadlly by GSASII. There is a few reasons why I have done this, but just to make it short it is, some structures (especially coming from COD) will 'break' GSASII (It will have some issue during refinement, leading to a FloatingPointError, which can only be fixed by restarting the script). Currently this is slow,, and I am still thinking on what is the best way to solve this.

This is the part I have "mocked" (you can see in the code for `test_solvers.py`). Basically, I used my own MP_API_KEY to get the results, then saved them to disk, and now when the tests runs it "fakes" the `MPRester.query()` command by just returning the saved data. The GSAS part is a bit slow, but as we are using an ephemeral database in the CI, it only needs to be done once for the entire set of tests. I actually switched to using `mongomock` rather than the full mongo service, as this can make it easier to test locally too without polluting your existing database.

>     2. Then after everything is downloaded we will do set of analysis (after everything is downloaded)
> 
> 
> I believe the cif.json issue is happening in the GSASII tester part, probably because there was an issue downloading the structures. This is why I think we should set CI with optimade MP, because even if we mock, in the end he still needs the structures.

This issue seems to be fixed by loading the proper MP data now. I am of the opinion that it is worth including these tests so that when OPTIMADE is implemented properly, you can see that the results don't change (or if they do, that it is controllable).

> I am sorry I am telling this now, I should had told you before exactly what the tests are doing.

No problem, I could piece it together from the code :)

You can see the tests running successfully here: https://github.com/ml-evs/Xerus/runs/5434514542?check_suite_focus=true

As you say, it is a bit slow at the moment (30 minutes per run) so perhaps they could be cut down a bit in the future. I'll leave it up to you to decide whether to merge or not!

**Comment by ml-evs** [comment]
Note, another change was to add a requests timeout to every querier. For some reason, by default, the requests library uses an infinite timeout, so if a server is down the queries will hang indefinitely. I added a setting for this.

**Comment by pedrobcst** [comment]
Thanks for the updates!

I think we are almost ready to merge. I am planning to create a new feature branch first and merge there to test few things on my end, let me know what you think (and even this makes sense or not). There is only two things I am wondering about.

1. Regarding the timeout: This is something Ive pondered about before. Actually I am opnion if one server is down, should we even let the analysis to go forward? I am wondering because, in case the database is already populated with some structures for a given chemical space, Xerus by default will not do any queries, so in the case one of the querier fails, there might be a chance we might have some missing structure. Altough, I made a quick implementation for trying to resync it needs to be manually ran (and this might not be ideal). Maybe I can add a logger that when some provider gives a timeout, it will be easily to track later on what needs to be resynced

2. I actually have to update the README with installation instructions and maybe the notebook to remove all the path hacks if they are not needed anymore. I was also wondering if it would be better to work on a new branch, to let this one be historically the same to what was published. Idk about that

And also, if you have some time down the line, I would appreciate if you could explain to me a bit more in details about how you set up the CI. I was actually stuck on that for a while :).

Sorry for the late replies, alot going on, but it is nice to have someone interseted and helping it make it better :)

**Comment by ml-evs** [comment]
> 1. Regarding the timeout: This is something Ive pondered about before. Actually I am opnion if one server is down, should we even let the analysis to go forward? I am wondering because, in case the database is already populated with some structures for a given chemical space, Xerus by default will not do any queries, so in the case one of the querier fails, there might be a chance we might have some missing structure. Altough, I made a quick implementation for trying to resync it needs to be manually ran (and this might not be ideal). Maybe I can add a logger that when some provider gives a timeout, it will be easily to track later on what needs to be resynced

This should be what happens now in this PR, if the database is down there will be an unhandled `requests.TimeoutError` which will end the analysis. Previously, it would just hang forever until the server responded.

> 2. I actually have to update the README with installation instructions and maybe the notebook to remove all the path hacks if they are not needed anymore. I was also wondering if it would be better to work on a new branch, to let this one be historically the same to what was published. Idk about that

I guess this is the bit that you will want to test at your end first :) It should be as easy as `pip install .`, which will also download all the requirements (currently repeated between requirements.txt and setup.cfg, but in future you could make the versions in setup.cfg more forgiving and pin specific tested versions in requirements.txt, or just scrap requirements.txt altogether).


> And also, if you have some time down the line, I would appreciate if you could explain to me a bit more in details about how you set up the CI. I was actually stuck on that for a while :).

Sure, happy to talk you through it. I am fairly free in the mornings (UTC) this week, if that would work for you? 09:00 UTC is 18:00 in Japan right?

> Sorry for the late replies, alot going on, but it is nice to have someone interseted and helping it make it better :)

No problem, I think we'd like to apply this within our system to some diffraction data we are collecting soon :)

**Comment by ml-evs** [comment]
> I was also wondering if it would be better to work on a new branch, to let this one be historically the same to what was published. Idk about that

Up to you really, I see you have the tagged release for v1 and of course git lets you rollback to wherever you want :) You could also archive releases on Zenodo (there is a nice automated GitHub integration for that) which gives you a DOI for each version and a concept DOI for the whole project.

**Comment by pedrobcst** [comment]
> Up to you really, I see you have the tagged release for v1 and of course git lets you rollback to wherever you want :) You could also archive releases on Zenodo (there is a nice automated GitHub integration for that) which gives you a DOI for each version and a concept DOI for the whole project.

Actually this might be a good idea. After thinking for a while, I think it can be fine to be not the same as historically in the paper as long as I keep the v1 release there and I keep the README updated and have it hosted on zenodo with DOI.

> This should be what happens now in this PR, if the database is down there will be an unhandled requests.TimeoutError which will end the analysis. Previously, it would just hang forever until the server responded.

This is amazing! Thanks for that. This will definetly make it better than just waiting forever for response (...looking at you OQMD).


> Sure, happy to talk you through it. I am fairly free in the mornings (UTC) this week, if that would work for you? 09:00 UTC is 18:00 in Japan right?

Yup! Thats fine for me. I think I can shoot you a message in Discord and we can set it up? I think I might be able to find you frm the MADICES discord or we can setup in another manner.

**Comment by pedrobcst** [comment]
Hi Evan,

I was testing locally and I found an issue. Currently
'''bash
pip install .
'''
Only install the main __init__.py. It doesnt not copy all the other files into sitepackage. So altough the tests can run from outside the folder (because he will be able to find other modules because it is inside the same folder), when trying to run outside of folder it will fail to find the packages (and also the reason where python run tcif.py is failing (atleast in my copy..)
I dont know if I am doing something wrong or not, but I will work on trying to get a fix of this. Might be just setup.py?

**Comment by ml-evs** [comment]
> Only install the main **init**.py. It doesnt not copy all the other files into sitepackage. So altough the tests can run from outside the folder (because he will be able to find other modules because it is inside the same folder), when trying to run outside of folder it will fail to find the packages (and also the reason where python run tcif.py is failing (atleast in my copy..)

I tried reinstalling this myself in a fresh environment and found the same problem. I've just pushed some changes in 2ab7771 that should fix this by adding the missing non-Python files to a MANIFEST.in, and making sure that the GSAS-II folder was recognised as a submodule. Could you try just `pip install .` again in a fresh environment?

I also added a test in the CI for importing the package from outside of the main folder.

> I dont know if I am doing something wrong or not, but I will work on trying to get a fix of this. Might be just setup.py?

The `setup.cfg` and `pyproject.toml` files should replace the `setup.py`, and I think this is the current "best practice" as setup.py could be too flexible for most use cases. Let me know if this works for you now!

**Comment by ml-evs** [comment]
> Yup! Thats fine for me. I think I can shoot you a message in Discord and we can set it up? I think I might be able to find you frm the MADICES discord or we can setup in another manner.

👍

**Comment by pedrobcst** [comment]
OK I have managed to do few tests and it seems to be running nicely. Few errors I had now were due to proxy issues on my side so I dont think they matter for now.

Just for a note to install I had to do the following:
```bash
conda create -n envname anaconda python==3.8 # This actually provides the fortran libraries that is needed by GSASII.  
git clone + pull (from your env)
pip install -e .
pytest -rs -vvv -m "not user"
```
The rests ran sucessfuly. Just pytest it failed but I think that is an issue on my side.
I am thinking on merging this on separate branch for now, and then do few edits in readme / notebooks, so we can finally remove all path hacks from everywhere.

Just a note, it seems that if we install in non-editable mode (pip install .), GSASII will break (cannot read CIFs). I will investigate this later on, but I feel that installing as non-editable (as a 'real package') warrants more changes (especially how to deal with config.conf from outside without having to go to site-packages etc..)

Anycase, its looking great. Thanks for the work.

**Comment by pedrobcst** [comment]
I realized that you are also modifying the optimade querier. Last night Ive been working on it a bit and I fixed few issues that I had previously made (such as if the extra_filters paramaters were empty things would simply not work). Ive been working on seperate branch (optimadev1), where I am also moving the current oqmd querier (which I found out it was not working well, it was missing alot of structures) to use optimade. I am wondering if we should merge this current PR into that branch and work there directly and after everything is working we merge in the main. It might be easier (Atleast for me)

**Comment by ml-evs** [comment]
> I realized that you are also modifying the optimade querier. Last night Ive been working on it a bit and I fixed few issues that I had previously made (such as if the extra_filters paramaters were empty things would simply not work). Ive been working on seperate branch (optimadev1), where I am also moving the current oqmd querier (which I found out it was not working well, it was missing alot of structures) to use optimade. I am wondering if we should merge this current PR into that branch and work there directly and after everything is working we merge in the main. It might be easier (Atleast for me)

I'll remove that commit for now as it was just something I was toying around with. Do you want me to push it to the optimadev1 branch?

**Comment by pedrobcst** [comment]
Yup! If possible, please commit there. This is was something I always also planning to handle so thanks for starting it, so hopefully we can get a working interface that can handle OQMD, COD, etc.

**Comment by ml-evs** [comment]
> Yup! If possible, please commit there. This is was something I always also planning to handle so thanks for starting it, so hopefully we can get a working interface that can handle OQMD, COD, etc.

I just pushed it to the optimadev1 branch directly

**Pull request merged**
